### ISSUE TITLE
Enviornment setting

### ISSUE THREAD

**Issue by frankchen121212** [arnabkmondal/scRAE#1]
Hello, thank you very much for your nice work.

I'm trying to reproduce your result, would you please share your environment settings? Eg. which tensorflow version and cuda environment that your experiments are based on.

Hope that you can help me.

Thank you!

**Comment by arnabkmondal** [comment]
Added requirements.yml. Hope that helps. Let me know if you need anything else.

**Comment by frankchen121212** [comment]
Thank you
