### ISSUE TITLE
The source code

### ISSUE THREAD

**Issue by 123kfl** [arnabkmondal/scRAE#2]
Hello, thank you very much for your nice work.

       I'm trying to reproduce your result,But I reproduced your code without evaluation index and result graph, could you please share your source code?
      Hope that you can help me.
       
      thank you!

**Comment by 123kfl** [comment]
Hello, thank you very much for your nice work.

   I'm trying to reproduce your result,Could you please explain the main work of each script in the code。
   Hope that you can help me.
   
  thank you! @arnabkmondal

**Comment by arnabkmondal** [comment]
Once you clone the repository, you may execute zeisel.sh.

**Comment by 123kfl** [comment]
Sorry to bother you again, Because I am a beginner,I would like to ask which repository&nbsp;is the clone?
I hope you can reply！
thank you!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arnabkmondal/scRAE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月8日(星期二) 晚上7:40
***@***.***&gt;;
抄送:&nbsp;"( •͈ᴗ⁃͈)ᓂ- - ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [arnabkmondal/scRAE] The source code (Issue #2)





 
Once you clone the repository, you may execute zeisel.sh.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by arnabkmondal** [comment]
Go to the url: https://github.com/arnabkmondal/scRAE
Click on the green color drop down button Code and then click on Download ZIP. Once the download is complete unzip. Then execute zeisel.sh in your terminal.

**Comment by 123kfl** [comment]
Thank you



---Original---
From: "Arnab Kumar ***@***.***&gt;
Date: Tue, Mar 8, 2022 23:01 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [arnabkmondal/scRAE] The source code (Issue #2)




 
Go to the url: https://github.com/arnabkmondal/scRAE
 Click on the green color drop down button Code and then click on Download ZIP. Once the download is complete unzip. Then execute zeisel.sh in your terminal.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 123kfl** [comment]
Thanks again for your reply. Regarding running the Zeisel.sh file you said in your reply, I ran it at the beginning, but there was no output, and when I ran the python file provided by you on GitHub, only the parameters mentioned in the paper came out. The proposed indicators and experimental results are not available. How to solve this situation? Again please can you help me!
Hope you reply me！
Thank you!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arnabkmondal/scRAE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月8日(星期二) 晚上11:01
***@***.***&gt;;
抄送:&nbsp;"( ?????)?- - ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [arnabkmondal/scRAE] The source code (Issue #2)





 
Go to the url: https://github.com/arnabkmondal/scRAE
 Click on the green color drop down button Code and then click on Download ZIP. Once the download is complete unzip. Then execute zeisel.sh in your terminal.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
